export class Circuiti
{
static lista=[
  {
    "circuitId": 1,
    "circuitRef": "albert park",
    "name": "Albert Park Grand Prix Circuit", //
    "location": "Melbourne",
    "country": "Australia",
    "lat": -37.8497,
    "lng": 144.968,
    "alt": 10,
    "url": "http://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit",
    "Lunghezza":	"5303 m",
    "Curve":	16,
    "Inaugurazione":	1996,
    "TempoRecord":	"1.24.125",
    "Detentore": "Michael Schumacher",
    "image": "https://media4.speedcafe.com/wp-content/uploads/2019/03/Albert-Park-1200x821.jpg"
  },
  {
    "circuitId": 2,
    "circuitRef": "sepang",
    "name": "Sepang International Circuit", //
    "location": "Kuala Lumpur",
    "country": "Malesia",
    "lat": 2.76083,
    "lng": 101.738,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Sepang_International_Circuit",
    "Lunghezza":	"5543 m",
    "Curve":	15,
    "Inaugurazione":	1998,
    "TempoRecord":	"1.34.080",
    "Detentore": "Sebastian Vettel",
    "image": "https://www.drivingitalia.net/uploads/monthly_2017_09/59ce1b059ed92_1064_ZymQnnzE_large(1).jpg.da2c83cdb6c2173e60a3c7f0908d5195.jpg"
  },
  {
    "circuitId": 3,
    "circuitRef": "bahrain",
    "name": "Bahrain International Circuit", //
    "location": "Sakhir",
    "country": "Bahrain",
    "lat": 26.0325,
    "lng": 50.5106,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Bahrain_International_Circuit",
    "Lunghezza":	"5412 m",
    "Curve":	15,
    "Inaugurazione":	2004,
    "TempoRecord":	"1.31.447",
    "Detentore": "Pedro de la Rosa",
    "image": "https://www.funoanalisitecnica.com/wp-content/uploads/2021/03/111.jpg"
  },
  {
    "circuitId": 4,
    "circuitRef": "catalunya",
    "name": "Circuit de Barcelona-Catalunya", //
    "location": "Montmeló",
    "country": "Spagna",
    "lat": 41.57,
    "lng": 2.26111,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya",
    "Lunghezza":	"4675 m",
    "Curve":	16,
    "Inaugurazione":	1991,
    "TempoRecord":	"1.18.183",
    "Detentore": "Valtteri Bottas",
    "image": "https://c1.wallpaperflare.com/preview/427/723/786/barcelona-building-circuit-de-catalunya-course.jpg"
  },
  {
    "circuitId": 5,
    "circuitRef": "istanbul", //
    "name": "Istanbul Park",
    "location": "Istanbul",
    "country": "Turchia",
    "lat": 40.9517,
    "lng": 29.405,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Istanbul_Park",
    "Lunghezza":	"5338 m",
    "Curve":	14,
    "Inaugurazione":	2005,
    "TempoRecord":	"1.24.770",
    "Detentore": "	Juan Pablo Montoya",
    "image": "https://www.formula1.com/content/dam/fom-website/manual/Misc/2020/2020races/Turkey/GENERAL%20AERIAL%20SHOT%20AND%20CORNER%201.jpg"
  },
  {
    "circuitId": 6,
    "circuitRef": "monaco", //
    "name": "Circuit de Monaco",
    "location": "Monte-Carlo",
    "country": "Monaco",
    "lat": 43.7347,
    "lng": 7.42056,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_de_Monaco",
    "Lunghezza":	"3337 m",
    "Curve":	19,
    "Inaugurazione":	1929,
    "TempoRecord":	"1.14.260",
    "Detentore": "Max Verstappen",
    "image": "https://wallpapercave.com/wp/wp3067733.jpg"
  },
  {
    "circuitId": 7,
    "circuitRef": "villeneuve", //
    "name": "Circuit Gilles Villeneuve",
    "location": "Montreal",
    "country": "Canada",
    "lat": 45.5,
    "lng": -73.5228,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve",
    "Lunghezza":	"	4361 m",
    "Curve":	14,
    "Inaugurazione":	1978,
    "TempoRecord":	"1.13.078",
    "Detentore": "Valtteri Bottas",
    "image": "https://www.f1-fansite.com/wp-content/uploads/2012/07/F1-Fansite.com-HD-Wallpaper-2012-Canada-F1-GP_25.jpg"
  },
  {
    "circuitId": 8,
    "circuitRef": "magny cours", //
    "name": "Circuit de Nevers Magny-Cours",
    "location": "Magny Cours",
    "country": "Francia",
    "lat": 46.8642,
    "lng": 3.16361,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_de_Nevers_Magny-Cours",
    "Lunghezza":	"	4411 m",
    "Curve":	17,
    "Inaugurazione":	1960,
    "TempoRecord":	"1.15.377",
    "Detentore": "Michael Schumacher",
    "image": "https://images2-motori.gazzettaobjects.it/corsedimoto/2020/09/29/06/30/cover-magny-cours-375x289.jpeg"
  },
  {
    "circuitId": 9,
    "circuitRef": "silverstone", //
    "name": "Silverstone Circuit",
    "location": "Silverstone",
    "country": "Regno Unito",
    "lat": 52.0786,
    "lng": -1.01694,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Silverstone_Circuit",
    "Lunghezza":	"	5891 m",
    "Curve":	18,
    "Inaugurazione":	1947,
    "TempoRecord":	"1.27.097",
    "Detentore": "Max Verstappen",
    "image": "https://populous.com/wp-content/uploads/2018/01/POP_07_3037_00_3037_Silverstone_Exterior_Day1_DarrenHeath_FullRights.jpg"
  },
  {
    "circuitId": 10,
    "circuitRef": "hockenheimring", //
    "name": "Hockenheimring",
    "location": "Hockenheim",
    "country": "Germania",
    "lat": 49.3278,
    "lng": 8.56583,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Hockenheimring",
    "Lunghezza":	"	4574 m",
    "Curve":	17,
    "Inaugurazione":	1932,
    "TempoRecord":	"1.13.780",
    "Detentore": "	Kimi Räikkönen",
    "image": "https://www.thenationalnews.com/image/policy:1.48579:1498923355/image/jpeg.jpg?f=16x9&w=1024&$p$f$w=2589da4"
  },
  {
    "circuitId": 11,
    "circuitRef": "hungaroring", //
    "name": "Hungaroring",
    "location": "Budapest",
    "country": "Ungheria",
    "lat": 47.5789,
    "lng": 19.2486,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Hungaroring",
    "Lunghezza":	"	4381 m",
    "Curve":	14,
    "Inaugurazione":	1986,
    "TempoRecord":	"1.16.627",
    "Detentore": "Lewis Hamilton",
    "image": "https://www.f1-fansite.com/wp-content/uploads/2013/07/F1-Fansite.com-HD-Wallpaper-2012-Hungary-F1-GP_17-618x278.jpg"
  },
  {
    "circuitId": 12,
    "circuitRef": "valencia", //
    "name": "Valencia Street Circuit",
    "location": "Valencia",
    "country": "Spagna",
    "lat": 39.4589,
    "lng": -0.331667,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Valencia_Street_Circuit",
    "Lunghezza":	"	5419 m",
    "Curve":	25,
    "Inaugurazione":	2008,
    "TempoRecord":	"1.38.683",
    "Detentore": "Timo Glock",
    "image": "https://www.formulapassion.it/wp-content/uploads/2019/11/Circuito-Ricardo-Tormo-Valencia-666x433.jpg"
  },
  {
    "circuitId": 13,
    "circuitRef": "spa",
    "name": "Circuit de Spa-Francorchamps", //
    "location": "Spa",
    "country": "Belgio",
    "lat": 50.4372,
    "lng": 5.97139,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps",
    "Lunghezza":	"	7004 m",
    "Curve":	19,
    "Inaugurazione":		1924,
    "TempoRecord":	"1.46.286",
    "Detentore": "Valtteri Bottas",
    "image": "https://c4.wallpaperflare.com/wallpaper/73/960/931/spa-francorchamps-circuit-wallpaper-preview.jpg"
  },
  {
    "circuitId": 14,
    "circuitRef": "monza", //
    "name": "Autodromo Nazionale di Monza",
    "location": "Monza",
    "country": "Italia",
    "lat": 45.6156,
    "lng": 9.28111,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza",
    "Lunghezza":	"	5793 m",
    "Curve":	11,
    "Inaugurazione":		1922,
    "TempoRecord":	"1.21.046",
    "Detentore": "Rubens Barrichello",
    "image": "https://prod.r3eassets.com/assets/content/track/monza-circuit-1670-signature-original.png"
  },
  {
    "circuitId": 15,
    "circuitRef": "marina bay", //
    "name": "Marina Bay Street Circuit",
    "location": "Marina Bay",
    "country": "Singapore",
    "lat": 1.2914,
    "lng": 103.864,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit",
    "Lunghezza":	"	5063 m",
    "Curve":	23,
    "Inaugurazione":		2008,
    "TempoRecord":	"1.41.905",
    "Detentore": "Kevin Magnussen",
    "image": "https://nazionaliditalia.it/wp-content/uploads/2018/09/marina-bay-street-circuit.jpg"
  },
  {
    "circuitId": 16,
    "circuitRef": "fuji", //
    "name": "Fuji Speedway",
    "location": "Oyama",
    "country": "Giappone",
    "lat": 35.3717,
    "lng": 138.927,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Fuji_Speedway",
    "Lunghezza":	"	4563 m",
    "Curve":	16,
    "Inaugurazione":		1965,
    "TempoRecord":	"1.18.426",
    "Detentore": "Felipe Massa",
    "image": "https://i.pinimg.com/originals/b4/88/18/b488188f570aaf3b3a34ed593bc2bda7.jpg"
  },
  {
    "circuitId": 17,
    "circuitRef": "shanghai", //
    "name": "Shanghai International Circuit",
    "location": "Shanghai",
    "country": "Cina",
    "lat": 31.3389,
    "lng": 121.22,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Shanghai_International_Circuit",
    "Lunghezza":	"	5451 m",
    "Curve":	16,
    "Inaugurazione":	2004,
    "TempoRecord":	"	1.31.095",
    "Detentore": "Sebastian Vettel",
    "image": "https://f1grandprix.motorionline.com/wp-content/uploads/2019/04/anteprima-gp-cina-2019.jpg"
  },
  {
    "circuitId": 18,
    "circuitRef": "interlagos", //
    "name": "Autódromo José Carlos Pace",
    "location": "São Paulo",
    "country": "Brasile",
    "lat": -23.7036,
    "lng": -46.6997,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace",
    "Lunghezza":	"	4309 m",
    "Curve":	15,
    "Inaugurazione":	1940,
    "TempoRecord":	"	1.10.540",
    "Detentore": "Valtteri Bottas",
    "image": "https://cdn1.snaplap.net/wp-content/uploads/2015/08/08081034/interlagos-circuit.jpg"
  },
  {
    "circuitId": 19,
    "circuitRef": "indianapolis", //
    "name": "Indianapolis Motor Speedway",
    "location": "Indianapolis",
    "country": "USA",
    "lat": 39.795,
    "lng": -86.2347,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Indianapolis_Motor_Speedway",
    "Lunghezza":	"	4192 m",
    "Curve":	13,
    "Inaugurazione":	1909,
    "TempoRecord":	"	1.10.399",
    "Detentore": "Rubens Barrichello",
    "image": "https://c1.wallpaperflare.com/preview/848/969/283/indianapolis-motor-speedway-aerial-view-auto-racing-sports.jpg"
  },
  {
    "circuitId": 20,
    "circuitRef": "nurburgring", //
    "name": "Nürburgring",
    "location": "Nürburg",
    "country": "Germania",
    "lat": 50.3356,
    "lng": 6.9475,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/N%C3%BCrburgring",
    "Lunghezza":	"	5148 m",
    "Curve":	15,
    "Inaugurazione":	1927,
    "TempoRecord":	"	1.25.269",
    "Detentore": "Valtteri Bottas",
    "image": "https://www.assettocorsa.it/wp-content/uploads/Nordschleife-bgr02.jpg"
  },
  {
    "circuitId": 21,
    "circuitRef": "imola", //
    "name": "Autodromo Enzo e Dino Ferrari",
    "location": "Imola",
    "country": "Italia",
    "lat": 44.3439,
    "lng": 11.7167,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari",
    "Lunghezza":	"	4909 m",
    "Curve":	19,
    "Inaugurazione":	1953,
    "TempoRecord":	"1.15.484",
    "Detentore": "Lewis Hamilton",
    "image": "https://www.digital-news.it/img/palinsesti/2020/10/1604100112-gp-emilia-romagna.jpg"
  },
  {
    "circuitId": 22,
    "circuitRef": "suzuka", //
    "name": "Suzuka Circuit",
    "location": "Suzuka",
    "country": "Giappone",
    "lat": 34.8431,
    "lng": 136.541,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Suzuka_Circuit",
    "Lunghezza":	"	5807 m",
    "Curve":	18,
    "Inaugurazione":	1962,
    "TempoRecord":	"1.30.983",
    "Detentore": "Lewis Hamilton",
    "image": "https://i.pinimg.com/originals/e1/60/8a/e1608ae6880b3813e79996ea5fc017e6.jpg"
  },
  {
    "circuitId": 23,
    "circuitRef": "osterreichring", //
    "name": "A1-Ring",
    "location": "Spielburg",
    "country": "Austria",
    "lat": 47.2197,
    "lng": 14.7647,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/A1-Ring",
    "Lunghezza":	"	4318 m",
    "Curve":	10,
    "Inaugurazione":	1996,
    "TempoRecord":	"1.05.619",
    "Detentore": "Carlos Sainz Jr.",
    "image": "https://www.formulapassion.it/wp-content/uploads/2013/07/Red-Bull-Ring-990x659.jpg"
  },
  {
    "circuitId": 24,
    "circuitRef": "yas marina", //
    "name": "Yas Marina Circuit",
    "location": "Abu Dhabi",
    "country": "Emirati Arabi Uniti",
    "lat": 24.4672,
    "lng": 54.6031,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Yas_Marina_Circuit",
    "Lunghezza":	"	5554 m",
    "Curve":	21,
    "Inaugurazione":	2009,
    "TempoRecord":	"1.39.283",
    "Detentore": "Lewis Hamilton",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/15/9d/d7/64/90-minute-small-group.jpg"
  },
  {
    "circuitId": 25,
    "circuitRef": "galvez", //
    "name": "Autódromo Juan y Oscar Gálvez",
    "location": "Buenos Aires",
    "country": "Argentina",
    "lat": -34.6943,
    "lng": -58.4593,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Oscar_Alfredo_G%C3%A1lvez",
    "Lunghezza":	"	4259 m",
    "Curve":	16,
    "Inaugurazione":	1952,
    "TempoRecord":	"	1.27.981",
    "Detentore": "Gerhard Berger",
    "image": "https://www.statsf1.com/photos/circuits/buenos.jpg"
  },
  {
    "circuitId": 26,
    "circuitRef": "jerez", //
    "name": "Circuito de Jerez",
    "location": "Jerez de la Frontera",
    "country": "Spagna",
    "lat": 36.7083,
    "lng": -6.03417,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuito_Permanente_de_Jerez",
    "Lunghezza":	"	4423 m",
    "Curve":	13,
    "Inaugurazione":	1985,
    "TempoRecord":	"1.18",
    "Detentore": "Heinz-Harald Frentzen",
    "image": "https://f1grandprix.motorionline.com/wp-content/uploads/2021/02/Test_Pirelli_Ferrari_Jerez_-2.jpg"
  },
  {
    "circuitId": 27,
    "circuitRef": "estoril",
    "name": "Autódromo do Estoril", //
    "location": "Estoril",
    "country": "Portogallo",
    "lat": 38.7506,
    "lng": -9.39417,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aut%C3%B3dromo_do_Estoril",
    "Lunghezza":	"	4182 m",
    "Curve":	13,
    "Inaugurazione":	1972,
    "TempoRecord":	"1.14.859",
    "Detentore": "Damon Hill",
    "image": "https://i1.wp.com/f1ingenerale.com/wp-content/uploads/2020/10/aerial.jpg?resize=840%2C473&ssl=1"
  },
  {
    "circuitId": 28,
    "circuitRef": "okayama", //
    "name": "Okayama International Circuit",
    "location": "Okayama",
    "country": "Giappone",
    "lat": 34.915,
    "lng": 134.221,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/TI_Circuit",
    "Lunghezza":	"	3703 m",
    "Curve":	13,
    "Inaugurazione":	1992,
    "TempoRecord":	"1.10.218",
    "Detentore": "Ayrton Senna",
    "image": "https://undiecar.com/files/okayama-background.jpg"
  },
  {
    "circuitId": 29,
    "circuitRef": "adelaide",
    "name": "Adelaide Street Circuit", //
    "location": "Adelaide",
    "country": "Australia",
    "lat": -34.9272,
    "lng": 138.617,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Adelaide_Street_Circuit",
    "Lunghezza":	"	3780 m",
    "Curve":	16,
    "Inaugurazione":	1985,
    "TempoRecord":	"	1.15.381",
    "Detentore": "Damon Hill",
    "image": "https://f1grandprix.motorionline.com/wp-content/uploads/2021/01/GP_Australia_rischio_rinvio_.jpg"
  },
  {
    "circuitId": 30,
    "circuitRef": "kyalami", //
    "name": "Kyalami",
    "location": "Midrand",
    "country": "Sud Africa",
    "lat": -25.9894,
    "lng": 28.0767,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Kyalami",
    "Lunghezza":	"	4522 m",
    "Curve":	16,
    "Inaugurazione":	1961,
    "TempoRecord":	"	1.17.578",
    "Detentore": "Nigel Mansell",
    "image": "https://www.formulapassion.it/wp-content/uploads/2016/09/Kyalami_2-Custom-587x444.jpg"
  },
  {
    "circuitId": 31,
    "circuitRef": "donington", //
    "name": "Donington Park",
    "location": "Castle Donington",
    "country": "Regno Unito",
    "lat": 52.8306,
    "lng": -1.37528,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Donington_Park",
    "Lunghezza":	"	4020 m",
    "Curve":	12,
    "Inaugurazione":	1931,
    "TempoRecord":	"	1.10.458",
    "Detentore": "Alain Prost",
    "image": "https://cdn-1.motorsport.com/static/img/amp/5000000/5030000/5036000/5036100/5036142/s6_1006433/1006433.jpg"
  },
  {
    "circuitId": 32,
    "circuitRef": "rodriguez",
    "name": "Autódromo Hermanos Rodríguez", //
    "location": "Mexico City",
    "country": "Messico",
    "lat": 19.4042,
    "lng": -99.0907,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez",
    "Lunghezza":	"	4304 m",
    "Curve":	17,
    "Inaugurazione":	1962,
    "TempoRecord":	"	1.18.741",
    "Detentore": "	Valtteri Bottas",
    "image": "https://i.pinimg.com/originals/56/f5/32/56f532f11f5acf2b8047cdad48f88bb6.jpg"
  },
  {
    "circuitId": 33,
    "circuitRef": "phoenix", //
    "name": "Phoenix street circuit",
    "location": "Phoenix",
    "country": "USA",
    "lat": 33.4479,
    "lng": -112.075,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Phoenix_street_circuit",
    "Lunghezza":	"	3720 m",
    "Curve":	15,
    "Inaugurazione":	1989,
    "TempoRecord":	"	1.21.434",
    "Detentore": "	Ayrton Senna",
    "image": "https://2.bp.blogspot.com/-5QZEi84vZ08/UyMm73B4QRI/AAAAAAAAOhc/tmOKw6z3Q2Y/s1600/ayrton_senna_gp_usa_1991_getty.jpg"
  },
  {
    "circuitId": 34,
    "circuitRef": "ricard", //
    "name": "Circuit Paul Ricard",
    "location": "Le Castellet",
    "country": "Francia",
    "lat": 43.2506,
    "lng": 5.79167,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Paul_Ricard_Circuit",
    "Lunghezza":	"	5842 m",
    "Curve":	15,
    "Inaugurazione":	1970,
    "TempoRecord":	"	1.32.740",
    "Detentore": "	Sebastian Vettel",
    "image": "https://metropolitanmagazine.it/wp-content/uploads/2019/06/1-paul-richard-copertina.jpg"
  },
  {
    "circuitId": 35,
    "circuitRef": "yeongam",
    "name": "Korean International Circuit", //
    "location": "Yeongam County",
    "country": "Korea del Sud",
    "lat": 34.7333,
    "lng": 126.417,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Korean_International_Circuit",
    "Lunghezza":	"	5615 m",
    "Curve":	18,
    "Inaugurazione":	2010,
    "TempoRecord":	"	1.39.605",
    "Detentore": "	Sebastian Vettel",
    "image": "https://www.formulapassion.it/wp-content/uploads/2012/10/Yeongam-circui-corea-veduta.jpg"
  },
  {
    "circuitId": 36,
    "circuitRef": "jacarepagua", //
    "name": "Autódromo Internacional Nelson Piquet",
    "location": "Rio de Janeiro",
    "country": "Brasile",
    "lat": -22.9756,
    "lng": -43.395,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Internacional_Nelson_Piquet",
    "Lunghezza":	"	4933 m",
    "Curve":	11,
    "Inaugurazione":	1977,
    "TempoRecord":	"	1.32.507",
    "Detentore": "	Riccardo Patrese",
    "image": "http://www.bonur.it/fantacircuiti/wp-content/uploads/2018/11/JacarepaguaHDxr.jpg"
  },
  {
    "circuitId": 37,
    "circuitRef": "detroit", //
    "name": "Detroit Street Circuit",
    "location": "Detroit",
    "country": "USA",
    "lat": 42.3298,
    "lng": -83.0401,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Detroit_street_circuit",
    "Lunghezza":	"	4023 m",
    "Curve":	22,
    "Inaugurazione":	1982,
    "TempoRecord":	"	1.40.464",
    "Detentore": "Ayrton Senna",
    "image": "https://detroitgp.com/assets/belle-isle-aerial.jpg"
  },
  {
    "circuitId": 38,
    "circuitRef": "brands hatch", //
    "name": "Brands Hatch",
    "location": "Kent",
    "country": "Regno unito",
    "lat": 51.3569,
    "lng": 0.263056,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Brands_Hatch",
    "Lunghezza":	"	3703 m",
    "Curve":	 9,
    "Inaugurazione":	1964,
    "TempoRecord":	"	1.06.961",
    "Detentore": "Nelson Piquet",
    "image": "https://1.bp.blogspot.com/-GXxXurv2ZGQ/Uu2Hegn1QyI/AAAAAAAANk4/G19cs9dvVtU/s1600/Brands-from-the-air.jpg"
  },
  {
    "circuitId": 39,
    "circuitRef": "zandvoort", //
    "name": "Circuit Park Zandvoort",
    "location": "Zandvoort",
    "country": "Olanda",
    "lat": 52.3888,
    "lng": 4.54092,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_Zandvoort",
    "Lunghezza":	"	4259 m",
    "Curve":	 14,
    "Inaugurazione":	1939,
    "TempoRecord":	"	1.19.511",
    "Detentore": "Max Verstappen",
    "image": "https://f1grandprix.motorionline.com/wp-content/uploads/2019/12/zandvoort-f1-gp-olanda.jpg"
  },
  {
    "circuitId": 40,
    "circuitRef": "zolder", //
    "name": "Zolder",
    "location": "Heusden-Zolder",
    "country": "Belgio",
    "lat": 50.9894,
    "lng": 5.25694,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Zolder",
    "Lunghezza":	"	3977 m",
    "Curve":	 10,
    "Inaugurazione":	1963,
    "TempoRecord":	"	1.12",
    "Detentore": "Sébastien Bourdais",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Circuit_Zolder_6-11-2008_16-29-22.jpg/440px-Circuit_Zolder_6-11-2008_16-29-22.jpg"
  },
  {
    "circuitId": 41,
    "circuitRef": "dijon", //
    "name": "Dijon-Prenois",
    "location": "Dijon",
    "country": "Francia",
    "lat": 47.3625,
    "lng": 4.89913,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Dijon-Prenois",
    "Lunghezza":	"	3801 m",
    "Curve":	 8,
    "Inaugurazione":	1972,
    "TempoRecord":	"	1.05.257",
    "Detentore": "Alain Prost",
    "image": "https://labonbonnierehotel.fr/wp-content/uploads/2018/08/circuit-de-dijon-prenois.jpg"
  },
  {
    "circuitId": 42,
    "circuitRef": "dallas", //
    "name": "Fair Park",
    "location": "Dallas",
    "country": "USA",
    "lat": 32.7774,
    "lng": -96.7587,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Fair_Park",
    "Lunghezza":	"	3901 m",
    "Curve":	 23,
    "Inaugurazione":	1984,
    "TempoRecord":	"	1.37.041",
    "Detentore": "Nigel Mansell",
    "image": "https://f1grandprix.motorionline.com/wp-content/uploads/2015/02/f1-dallas84.jpg"
  },
  {
    "circuitId": 43,
    "circuitRef": "long beach",
    "name": "Long Beach", //
    "location": "California",
    "country": "USA",
    "lat": 33.7651,
    "lng": -118.189,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Long_Beach,_California",
    "Lunghezza":	"	3167 m",
    "Curve":	 13,
    "Inaugurazione":	1975,
    "TempoRecord":	"	1.06.886",
    "Detentore": "Sébastien Bourdais",
    "image": "https://cdn.shortpixel.ai/spai/w_656+q_lossy+ret_img+to_webp/https://www.f1sport.it/wp-content/uploads/2016/06/long_beach_start_1981.jpg"
  },
  {
    "circuitId": 44,
    "circuitRef": "las vegas", //
    "name": "Las Vegas Street Circuit",
    "location": "Nevada",
    "country": "USA",
    "lat": 36.1162,
    "lng": -115.174,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Las_Vegas,_Nevada",
    "Lunghezza":	"	3650 m",
    "Curve":	 14,
    "Inaugurazione":	1981,
    "TempoRecord":	"	1.19.639",
    "Detentore": "Michele Alboreto",
    "image": "https://i.redd.it/u75zr2gtxkf21.jpg"
  },
  {
    "circuitId": 45,
    "circuitRef": "jarama", //
    "name": "Jarama",
    "location": "Madrid",
    "country": "Spagna",
    "lat": 40.6171,
    "lng": -3.58558,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuito_Permanente_Del_Jarama",
    "Lunghezza":	"	3850 m",
    "Curve":	 13,
    "Inaugurazione":	1967,
    "TempoRecord":	"	1.16.44",
    "Detentore": "Gilles Villeneuve",
    "image": "https://cdn.motor1.com/images/mgl/mmYme/s1/reasfaltado-del-circuito-del-jarama.jpg"
  },
  {
    "circuitId": 46,
    "circuitRef": "watkins glen", //
    "name": "Watkins Glen",
    "location": "New York State",
    "country": "USA",
    "lat": 42.3369,
    "lng": -76.9272,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Watkins_Glen_International",
    "Lunghezza":	"	5552  m",
    "Curve":	 15,
    "Inaugurazione":	1948,
    "TempoRecord":	"	1.35.207",
    "Detentore": "Johannes van Overbeek",
    "image": "https://preview.redd.it/gxqrs1jnk5361.jpg?width=1024&format=pjpg&auto=webp&s=55cc9a0e394c748e6945b933f12c5cbb9101af99"
  },
  {
    "circuitId": 47,
    "circuitRef": "anderstorp", //
    "name": "Scandinavian Raceway",
    "location": "Anderstorp",
    "country": "Svezia",
    "lat": 57.2653,
    "lng": 13.6042,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Scandinavian_Raceway",
    "Lunghezza":	"	4025  m",
    "Curve":	 8,
    "Inaugurazione":	1968,
    "TempoRecord":	"	1.24.836",
    "Detentore": "Niki Lauda",
    "image": "https://sportscar365.com/wp-content/uploads/2019/09/AnderstorpDTM.jpg"
  },
  {
    "circuitId": 48,
    "circuitRef": "mosport", //
    "name": "Mosport International Raceway",
    "location": "Ontario",
    "country": "Canada",
    "lat": 44.0481,
    "lng": -78.6756,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Mosport",
    "Lunghezza":	"	3957  m",
    "Curve":	 10,
    "Inaugurazione":	1961,
    "TempoRecord":	"	1.05.823",
    "Detentore": "Marco Werner",
    "image": "https://picolio.auto123.com/art-images/140566/mosport-aerial-inline.jpg"
  },
  {
    "circuitId": 49,
    "circuitRef": "montjuic", //
    "name": "Montjuïc",
    "location": "Barcelona",
    "country": "Spagna",
    "lat": 41.3664,
    "lng": 2.15167,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Montju%C3%AFc_circuit",
    "Lunghezza":	"	3791  m",
    "Curve":	 11,
    "Inaugurazione":	1932,
    "TempoRecord":	"	1.21.800",
    "Detentore": "Ronnie Peterson",
    "image": "https://i.pinimg.com/originals/b0/3f/78/b03f78784f57baf3a8c2ee8582dfc771.jpg"
  },
  {
    "circuitId": 50,
    "circuitRef": "nivelles",
    "name": "Nivelles-Baulers", //
    "location": "Brussels",
    "country": "Belgio",
    "lat": 50.6211,
    "lng": 4.32694,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Nivelles-Baulers",
    "Lunghezza":	"	3724  m",
    "Curve":	 7,
    "Inaugurazione":	1972,
    "TempoRecord":	"	1.09.82",
    "Detentore": "Clay Regazzoni",
    "image": "https://3.bp.blogspot.com/-1N6pWtq6Juk/UwJt_rGTy0I/AAAAAAAANtM/A-cn8OGMajo/w1200-h630-p-k-no-nu/72bel10.jpg"
  },
  {
    "circuitId": 51,
    "circuitRef": "charade", //
    "name": "Charade Circuit",
    "location": "Clermont-Ferrand",
    "country": "Francia",
    "lat": 45.7472,
    "lng": 3.03889,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Charade_Circuit",
    "Lunghezza":	"	8055  m",
    "Curve":	 51,
    "Inaugurazione":	1958,
    "TempoRecord":	"	2.53.9",
    "Detentore": "Chris Amon",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEEr9Sv9VgCcwUGUnOdGeoF6RHcgVB5AwJ_Xtfyq_4VzIvXUUOPhSYJo4aG77Xlfsm4lk&usqp=CAU"
  },
  {
    "circuitId": 52,
    "circuitRef": "tremblant", //
    "name": "Circuit Mont-Tremblant",
    "location": "Quebec",
    "country": "Canada",
    "lat": 46.1877,
    "lng": -74.6099,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_Mont-Tremblant",
    "Lunghezza":	"	4265  m",
    "Curve":	 15,
    "Inaugurazione":	1964,
    "TempoRecord":	"	1.16.776",
    "Detentore": "Tristan Gommendy",
    "image": "https://lecircuit.com/wp-content/uploads/2017/06/1001.jpg"
  },
  {
    "circuitId": 53,
    "circuitRef": "essarts", //
    "name": "Rouen-Les-Essarts",
    "location": "Rouen",
    "country": "Francia",
    "lat": 49.3306,
    "lng": 1.00458,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Rouen-Les-Essarts",
    "Lunghezza":	"	6542  m",
    "Curve":	 13,
    "Inaugurazione":	1950,
    "TempoRecord":	"	2.11.400",
    "Detentore": "Jack Brabham",
    "image": "http://www.contagiriblog.com/wp-content/uploads/2013/12/Rouen.jpg"
  },
  {
    "circuitId": 54,
    "circuitRef": "lemans", //
    "name": "Le Mans",
    "location": "Le Mans",
    "country": "Francia",
    "lat": 47.95,
    "lng": 0.224231,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_de_la_Sarthe#Bugatti_Circuit",
    "Lunghezza":	"	4185  m",
    "Curve":	 11,
    "Inaugurazione":	1996,
    "TempoRecord":	"	1.30.713",
    "Detentore": "Mika Häkkinen",
    "image": "https://img3.stcrm.it/images/23264978/700x/circuit-des-24-heures.jpg"

  },
  {
    "circuitId": 55,
    "circuitRef": "reims", //
    "name": "Reims-Gueux",
    "location": "Reims",
    "country": "Francia",
    "lat": 49.2542,
    "lng": 3.93083,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Reims-Gueux",
    "Lunghezza":	"	8347  m",
    "Curve":	 7,
    "Inaugurazione":	1926,
    "TempoRecord":	"	2.11.003",
    "Detentore": "Lorenzo Bandini",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/02/28/8f/54/grandstands.jpg"
  },
  {
    "circuitId": 56,
    "circuitRef": "george", //
    "name": "Prince George Circuit",
    "location": "Eastern Cape Province",
    "country": "Sud Africa",
    "lat": -33.0486,
    "lng": 27.8736,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Prince_George_Circuit",
    "Lunghezza":	"	3920  m",
    "Curve":	 8,
    "Inaugurazione":	1934,
    "TempoRecord":	"	1.25.100",
    "Detentore": "Jack Brabhman",
    "image": "https://www.automotorinews.it/wp-content/uploads/2021/04/F1-Kyalami.jpg"
  },
  {
    "circuitId": 57,
    "circuitRef": "zeltweg", //
    "name": "Zeltweg",
    "location": "Styria",
    "country": "Austria",
    "lat": 47.2039,
    "lng": 14.7478,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Zeltweg_Airfield",
    "Lunghezza":	"	3200  m",
    "Curve":	 4,
    "Inaugurazione":	1959,
    "TempoRecord":	"1.09.840",
    "Detentore": "Graham Hill",
    "image": "https://photos.motogp.com/2016/02/18/aerial-p-20150904-00414_10-austria-p-20150904-00414_hires-jpeg-24bit-rgb_0.big.jpg"
  },
  {
    "circuitId": 58,
    "circuitRef": "aintree", //
    "name": "Aintree",
    "location": "Liverpool",
    "country": "Regno Unito",
    "lat": 53.4769,
    "lng": -2.94056,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Aintree_Motor_Racing_Circuit",
    "Lunghezza":	"	4828  m",
    "Curve":	 8,
    "Inaugurazione":	1954,
    "TempoRecord":	"1.55.0",
    "Detentore": "Jim Clark",
    "image": "https://www.webbaviation.co.uk/aerial/_data/i/galleries/Merseyside/Liverpool/Aintree_Racecourse_ba08061ap-me.jpg"
  },
  {
    "circuitId": 59,
    "circuitRef": "boavista", //
    "name": "Circuito da Boavista",
    "location": "Oporto",
    "country": "Portogallo",
    "lat": 41.1705,
    "lng": -8.67325,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuito_da_Boavista",
    "Lunghezza":	"	4807  m",
    "Curve":	 20,
    "Inaugurazione":	1931,
    "TempoRecord":	"2.27.530",
    "Detentore": "John Surtees",
    "image": "http://www.velocidades.pt/wp-content/uploads/2013/07/anpac030713.jpg"
  },
  {
    "circuitId": 60,
    "circuitRef": "riverside", //
    "name": "Riverside International Raceway",
    "location": "California",
    "country": "USA",
    "lat": 33.937,
    "lng": -117.273,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Riverside_International_Raceway",
    "Lunghezza":	"	5271  m",
    "Curve":	 10 ,
    "Inaugurazione":	1957,
    "TempoRecord":	"1.54.4",
    "Detentore": "Stirling Moss",
    "image": "https://automotorfargio.files.wordpress.com/2017/12/454156_124051_4fe0002422_p.jpg?w=672"
  },
  {
    "circuitId": 61,
    "circuitRef": "avus", //
    "name": "AVUS",
    "location": "Berlin",
    "country": "Germania",
    "lat": 52.4806,
    "lng": 13.2514,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/AVUS",
    "Lunghezza":	"	8300  m",
    "Curve":	 4 ,
    "Inaugurazione":	1921,
    "TempoRecord":	"2.04.5",
    "Detentore": "Tony Brooks",
    "image": "https://2.bp.blogspot.com/-XMYleebqJbg/UvUluffy0aI/AAAAAAAANnw/acsCVlQK-kY/s1600/3389.jpg"
  },
  {
    "circuitId": 62,
    "circuitRef": "monsanto", //
    "name": "Monsanto Park Circuit",
    "location": "Lisbon",
    "country": "Portogallo",
    "lat": 38.7197,
    "lng": -9.20306,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Monsanto_Park_Circuit",
    "Lunghezza":	"	5440  m",
    "Curve":	 9 ,
    "Inaugurazione":	1954,
    "TempoRecord":	"2.05.070",
    "Detentore": "Stirling Moss",
    "image": "https://iberianmph.files.wordpress.com/2012/07/monsantof1c2012.jpg"
  },
  {
    "circuitId": 63,
    "circuitRef": "sebring", //
    "name": "Sebring International Raceway",
    "location": "Florida",
    "country": "USA",
    "lat": 27.4547,
    "lng": -81.3483,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Sebring_Raceway",
    "Lunghezza":    "	6020 m",
    "Curve":    17,
    "Inaugurazione":    1950,
    "TempoRecord":  "   1.40.124",
    "Detentore": "Fernando Alonso",
    "image": "https://media.motorbox.com/image/portimao/7/0/3/703994/703994-16x9-lg.jpg"
  },
  {
    "circuitId": 64,
    "circuitRef": "ain diab", //
    "name": "Ain Diab",
    "location": "Casablanca",
    "country": "Marocco",
    "lat": 33.5786,
    "lng": -7.6875,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Ain-Diab_Circuit",
    "Lunghezza":    "7618 m",
    "Curve":    8,
    "Inaugurazione":    1957,
    "TempoRecord":  "   2.22.5",
    "Detentore": "Stirling Moss",
    "image": "https://cdn-8.latimages.com/images/mgl/9mexy/s4/open-uri20120927-21855-1dbaihp.jpg"
  },
  {
    "circuitId": 65,
    "circuitRef": "pescara", //
    "name": "Pescara Circuit",
    "location": "Pescara",
    "country": "Italia",
    "lat": 42.475,
    "lng": 14.1508,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Pescara_Circuit",
    "Lunghezza":    "25579 m",
    "Curve":    15,
    "Inaugurazione":    1924,
    "TempoRecord":  "   9.44.6",
    "Detentore": "Juan Manuel Fangio",
    "image": "http://www.motoremotion.it/wp-content/uploads/2014/08/pescara57_01.x45578.jpg"
  },
  {
    "circuitId": 66,
    "circuitRef": "bremgarten", //
    "name": "Circuit Bremgarten",
    "location": "Bern",
    "country": "Svizzera",
    "lat": 46.9589,
    "lng": 7.40194,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_Bremgarten",
    "Lunghezza":    "7280 m",
    "Curve":    11,
    "Inaugurazione":    1931,
    "TempoRecord":  "   2.39.7",
    "Detentore": "Juan Manuel Fangio",
    "image": "https://millsf1.weebly.com/uploads/2/3/8/4/23842228/p1297.png"
  },
  {
    "circuitId": 67,
    "circuitRef": "pedralbes", //
    "name": "Circuit de Pedralbes",
    "location": "Barcelona",
    "country": "Spagna",
    "lat": 41.3903,
    "lng": 2.11667,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Pedralbes_Circuit",
    "Lunghezza":    "6316 m",
    "Curve":    6,
    "Inaugurazione":    1946,
    "TempoRecord":  "   2.10.59",
    "Detentore": "Alberto Ascari",
    "image": "https://img.redbull.com/images/c_fill,g_auto,w_1160,h_773/q_auto,f_auto/redbullcom/2016/05/10/1331793936938_2/spanish-grand-prix-pedralbes-1951"
  },
  {
    "circuitId": 68,
    "circuitRef": "buddh", //
    "name": "Buddh International Circuit",
    "location": "Uttar Pradesh",
    "country": "India",
    "lat": 28.3487,
    "lng": 77.5331,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Buddh_International_Circuit",
    "Lunghezza":    "5125 m",
    "Curve":    16,
    "Inaugurazione":    2011,
    "TempoRecord":  "   1.27.249",
    "Detentore": "Sebastian Vettel",
    "image": "https://www.livegp.it/wp-content/uploads/2020/03/budd_circuit-696x392.jpg"
  },
{
    "circuitId": 69,
    "circuitRef": "americas", //
    "name": "Circuit of the Americas",
    "location": "Austin",
    "country": "USA",
    "lat": 30.1328,
    "lng": -97.6411,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Circuit_of_the_Americas",
    "Lunghezza":    "5513 m",
    "Curve":    20,
    "Inaugurazione":    2012,
    "TempoRecord":  "   1.36.169",
    "Detentore": "Charles Leclerc",
    "image": "http://www.horsemoonpost.com/newsite/wp-content/uploads/2013/11/20131115-circuit-of-the-americas-from-the-air-660x480.jpg"
  },
  {
    "circuitId": 70,
    "circuitRef": "red bull ring", //
    "name": "Red Bull Ring",
    "location": "Spielburg",
    "country": "Austria",
    "lat": 47.2197,
    "lng": 14.7647,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Red_Bull_Ring",
    "Lunghezza":    "4318 m",
    "Curve":    10,
    "Inaugurazione": 1996,
    "TempoRecord":  "   1.05.619",
    "Detentore": "Carlos Sainz",
    "image": "https://www.formulapassion.it/wp-content/uploads/2013/07/Red-Bull-Ring-990x659.jpg"
  },
  {
    "circuitId": 71,
    "circuitRef": "sochi", //
    "name": "Sochi Autodrom",
    "location": "Sochi",
    "country": "Russia",
    "lat": 43.4057,
    "lng": 39.9578,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Sochi_Autodrom",
    "Lunghezza":    "   5848 m",
    "Curve":    18,
    "Inaugurazione":    2014,
    "TempoRecord":  "   1.35.761",
    "Detentore": "Lewis Hamilton",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/0c/90/ae/5f/the-sochi-circuit.jpg"
  },

  {
    "circuitId": 72,
    "circuitRef": "port imperial", //
    "name": "Port Imperial Street Circuit",
    "location": "New Jersey",
    "country": "USA",
    "lat": 40.7769,
    "lng": -74.0111,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Port_Imperial_Street_Circuit",
    "Lunghezza":    "5200 m",
    "Curve":    19,
    "Inaugurazione":    2021,
    "TempoRecord":  "   Not Any",
    "Detentore": "Not Any",
    "image": "https://image.routeyou.com/shrink/fit/400x300/ef2fbc340ffe5d6bd70fc8865bb1959c_a4fbe299dc1050547257590f88dc3f1a9c6b9132.jpg"
  },
  {
    "circuitId": 73,
    "circuitRef": "bak", //
    "name": "Baku City Circuit",
    "location": "Baku",
    "country": "Azerbaijan",
    "lat": 40.3725,
    "lng": 49.8533,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Baku_City_Circuit",
    "Lunghezza":    "6300 m",
    "Curve":    20,
    "Inaugurazione":    2016,
    "TempoRecord":  "1.41.009",
    "Detentore": "Charles Leclerc",
    "image": "https://sport.periodicodaily.com/wp-content/uploads/2019/04/f1-baku-circuito.jpg"
  },

  {
    "circuitId": 74,
    "circuitRef": "hanoi",
    "name": "Hanoi Street Circuit",
    "location": "Hanoi",
    "country": "Vietnam",
    "lat": 21.0166,
    "lng": 105.766,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Hanoi_Street_Circuit",
    "Lunghezza":    "   5613 m",
    "Curve":    23,
    "Inaugurazione":    2021,
    "TempoRecord":  "   Not Any",
    "Detentore": "Not Any",
    "image": "https://e0.365dm.com/20/03/1600x900/skysports-vietnam-gp-2020-hanoi_4944625.jpg"
  },
  {
    "circuitId": 75,
    "circuitRef": "portimao", //
    "name": "Autódromo Internacional do Algarve",
    "location": "Portimão",
    "country": "Portogallo",
    "lat": 37.227,
    "lng": -8.6267,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Algarve_International_Circuit",
    "Lunghezza":    "4653 m",
    "Curve":    15,
    "Inaugurazione":    2008,
    "TempoRecord":  "1.18.750",
    "Detentore": "Lewis Hamilton",
    "image": "https://images2-motori.gazzettaobjects.it/corsedimoto/2019/01/09/12/30/cover-portimao-e1510397300130-375x289.jpeg"
  },

  {
    "circuitId": 76,
    "circuitRef": "mugello", //
    "name": "Autodromo Internazionale del Mugello",
    "location": "Mugello",
    "country": "Italia",
    "lat": 43.9975,
    "lng": 11.3719,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Mugello_Circuit",
    "Lunghezza":    "5245 m",
    "Curve":    15,
    "Inaugurazione":    1974,
    "TempoRecord":  "1.18.833",
    "Detentore": "Lewis Hamilton",
    "image": "https://www.promoracing.it/media/circuiti/0317_Mugello_Elicottero_ambience.jpg"
  },
  {
    "circuitId": 77, //
    "circuitRef": "jeddah",
    "name": "Jeddah Street Circuit",
    "location": "Jeddah",
    "country": "Arabia Saudita",
    "lat": 21.5433,
    "lng": 39.1728,
    "alt": "\\N",
    "url": "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit",
    "Lunghezza":    "   6175 m",
    "Curve":    27,
    "Inaugurazione":    2021,
    "TempoRecord":  "   Not Any",
    "Detentore": "Not Any",
    "image": "https://cdn-autosprint.corrieredellosport.it/images/2020/11/20/145242843-f5585622-10b6-4bea-a8cd-8f81ba6b5ae6.jpg"
  }
]
}
