export class Piloti
{
static listaPil=[
  {
    "driverId": 1,
    "firstName": "Lewis",
    "lastName": "Hamilton",
    "driverRef": "hamilton",
    "code": "HAM",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col/image.png",
    "number": 44,
    "car": "MERCEDES",
    "dateOfBirth": "07/01/1985",
    "nationality": "Inglese",
    "placeOfBirth": "Stevenage, Regno Unito",
    "biografy": "Il rispetto è duramente guadagnato in F1, ma Hamilton - ora Sir Lewis Hamilton per essere precisi - lo ha da tutti i suoi pari. Perché? Perché sanno che qualunque sia la pista, qualunque siano le condizioni, qualunque sia la situazione, quando la sua visiera si abbassa e le luci si spengono, è Hammertime.",
    "championshipsWon": 7,
    "podiums": 166,
    "participatingGPs": 267,
    "highestposGPs": '1 (x96)',
    "earnedPoint": 3803,
    "polePosition": 96,
    "lat": 51.9048,
    "lng": -0.19683
  },
  {
    "driverId": 2,
    "firstName": "SEBASTIAN",
    "lastName": "VETTEL",
    "driverRef": "vettel",
    "code": "VET",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col/image.png",
    "number": 5,
    "car": "ASTON MARTIN MERCEDES",
    "dateOfBirth": "03/07/1987",
    "nationality": "German",
    "placeOfBirth": "Heppenheim",
    "biografy": "Nato e cresciuto come un toro, poi un cavallino rampante, e ora il volto dell' Aston Martin, il ragazzo dei primi successi della F1 aveva vinto più di tutti, sotto solo a due piloti, nella storia quando aveva solo 26 anni, incluso il ritorno a titoli mondiali tra il 2010 e il 2013. Oltre ai suoi quattro titoli mondiali, può vantare più di 50 pole position e vittorie in gara.",
    "championshipsWon": 4,
    "podiums": 121,
    "participatingGPs": 259,
    "highestposGPs": '1 (x53)',
    "earnedPoint": 3018,
    "polePosition": 57,
    "lat": 49.6431,
    "lng": 8.66309
  },
  {
    "driverId": 3,
    "firstName": "Max",
    "lastName": "Verstappen",
    "driverRef": "verstappen",
    "code": "VER",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col/image.png",
    "number": 33,
    "car": "RED BULL RACING HONDA",
    "dateOfBirth": "30/09/1997",
    "nationality": "Dutch",
    "placeOfBirth": "Hasselt",
    "biografy": "Arrivato come il più giovane concorrente di Formula 1 a soli 17 anni, Verstappen ha spinto al limite la sua macchina, i suoi rivali e i libri dei record di questo sport. L'olandese dalla faccia da bambino e dal cuore di leone ha preso per le corna la Toro Rosso - e poi la Red Bull - con il suo stile di corsa istintivo. ",
    "championshipsWon": 0,
    "podiums": 43,
    "participatingGPs": 259,
    "highestposGPs": '1 (x11)',
    "earnedPoint": 1180,
    "polePosition": 4,
    "lat": 50.926,
    "lng": 5.285
  },
  {
    "driverId": 4,
    "firstName": "Valtteri",
    "lastName": "Bottas",
    "driverRef": "bottas",
    "code": "BOT",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col/image.png",
    "number": 77,
    "car": "MERCEDES",
    "dateOfBirth": "28/08/1989",
    "nationality": "Finnish",
    "placeOfBirth": "Nastola",
    "biografy": "Imparando il suo mestiere sulle strade finlandesi di ghiaccio e neve, è nato per essere un pilota di F1. Bottas spiega che se puoi guidare sulle strade ghiacciate della sua terra natia, puoi guidare ovunque. Poi c'è la mentalità finlandese: riservata, diligente e calma la corsia di sorpasso della F1 non lo turba.",
    "championshipsWon": 0,
    "podiums": 57,
    "participatingGPs": 159,
    "highestposGPs": '1 (x9)',
    "earnedPoint": 1528,
    "polePosition": 16,
    "lat": 60.094,
    "lng": 25.593
  },
  {
    "driverId": 5,
    "firstName": "Charles",
    "lastName": "Leclerc",
    "driverRef": "leclerc",
    "code": "LEC",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col/image.png",
    "number": 16,
    "car": "FERRARI",
    "dateOfBirth": "16/10/1997",
    "nationality": "Monegasque",
    "placeOfBirth": "Monte Carlo",
    "biografy": "Nato nell'idillio mediterraneo di Monaco, Leclerc è arrivato in F1 su un maremoto di aspettative.  Vincere i campionati consecutivi ha anche insegnato a Leclerc come gestire la pressione, un altro strumento utile nel grande stagno delle corse di Formula 1.",
    "championshipsWon": 0,
    "podiums": 12,
    "participatingGPs": 61,
    "highestposGPs": '1 (x2)',
    "earnedPoint": 421,
    "polePosition": 7,
    "lat": 43.7429,
    "lng": 7.42624
  },
  {
    "driverId": 6,
    "firstName": "Antonio",
    "lastName": "Giovinazzi",
    "driverRef": "giovinazzi",
    "code": "GIO",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/A/ANTGIO01_Antonio_Giovinazzi/antgio01.png.transform/2col/image.png",
    "number": 99,
    "car": "ALFA ROMEO RACING FERRARI",
    "dateOfBirth": "14/12/1993",
    "nationality": "Italian",
    "placeOfBirth": "Martina Franca",
    "biografy": 'È il destriero italiano in velocità dalla scuderia del Cavallino Rampante. Antonio Giovinazzi sventola la bandiera dellItalia mentre la nazione pazza del motorsport si impone per la sua prossima stella della F1. Il pilota pugliese riesce a farsi strada a pugni e ad eseguire un passaggio coraggioso.',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 42,
    "highestposGPs": '5 (x1)',
    "earnedPoint": 18,
    "polePosition": 0,
    "lat": 40.7024,
    "lng": 17.3383
  },
  {
    "driverId": 7,
    "firstName": "Fernando",
    "lastName": "Alonso",
    "driverRef": "alonso",
    "code": "ALO",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col/image.png",
    "number": 14,
    "car": "ALPINE RENAULT",
    "dateOfBirth": "29/07/1981",
    "nationality": "Spanish",
    "placeOfBirth": "Oviedo",
    "biografy": 'Ferocemente competitivo, Alonso non è timido per il suo talento, classificandosi come 9/10 "in tutto", e pochi a conoscenza sarebbero in disaccordo, con le sue prestazioni in F1 caratterizzate da velocità vertiginosa, brillante pensiero tattico, abilità da corsa esemplare, un rasoio - occhio acuto per i dettagli e una determinazione implacabile per vincere.',
    "championshipsWon": 2,
    "podiums": 97,
    "participatingGPs": 316,
    "highestposGPs": '1 (x32)',
    "earnedPoint": 1900,
    "polePosition": 22,
    "lat": 43.3638,
    "lng": -5.84917
  },
  {
    "driverId": 8,
    "firstName": "Lando",
    "lastName": "Norris",
    "driverRef": "norris",
    "code": "NOR",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col/image.png",
    "number": 4,
    "car": "MCLAREN MERCEDES",
    "dateOfBirth": "13/11/1999",
    "nationality": "British",
    "placeOfBirth": "",
    "biografy": 'La McLaren ha avuto ladolescente britannico nei loro libri per due anni prima di seguirlo rapidamente nella galassia di stelle della F1 nel 2019. Un petardo nella sua carriera da junior, con un debole per le pole position e le lotte ruota a ruota, Norris non ha permesso loro giù.',
    "championshipsWon": 0,
    "podiums": 2,
    "participatingGPs": 40,
    "highestposGPs": '3 (x2)',
    "earnedPoint": 173,
    "polePosition": 0,
    "lat": 51.4654,
    "lng": -2.58935
  },
  {
    "driverId": 9,
    "firstName": "Sergio",
    "lastName": "Perez",
    "driverRef": "perez",
    "code": "PER",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col/image.png",
    "number": 11,
    "car": "RED BULL RACING HONDA",
    "dateOfBirth": "26/1/1990",
    "nationality": "Mexican",
    "placeOfBirth": "Guadalajara",
    "biografy": 'È il combattente con un tocco gentile dalla terra del Lucha Libre. La reputazione di Perez in F1 è stata costruita su approcci opposti alle corse dei Gran Premi. É un combattente incisivo che si fa strada attraverso il branco e nei punti. Non ha mai paura di aggiungere un po di pepe ai suoi incontri in pista.',
    "championshipsWon": 0,
    "podiums": 10,
    "participatingGPs": 195,
    "highestposGPs": '1 (x1)',
    "earnedPoint": 716,
    "polePosition": 0,
    "lat": 20.7855,
    "lng": -103.346
  },
  {
    "driverId": 10,
    "firstName": "Daniel",
    "lastName": "Ricciardo",
    "driverRef": "ricciardo",
    "code": "RIC",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col/image.png",
    "number": 3,
    "car": "MCLAREN MERCEDES",
    "dateOfBirth": "01/07/1989",
    "nationality": "Australian",
    "placeOfBirth": "Perth",
    "biografy": 'Drivers beware because behind Ricciardo’s laidback persona and big grin is a razor-sharp racer with a bite.  The Australian combines all-out speed with impressive race craft. Never afraid to push to the limits if it means pulling off a pass, Ricciardo is a proven race-winner for Red Bull, capable of consistently finishing at the business end of the championship table.',
    "championshipsWon": 0,
    "podiums": 31,
    "participatingGPs": 190,
    "highestposGPs": '1 (x7)',
    "earnedPoint": 1173,
    "polePosition": 3,
    "lat": -31.9060,
    "lng": 115.862
  },
  {
    "driverId": 11,
    "firstName": "Carlos",
    "lastName": "Sainz",
    "driverRef": "sainz",
    "code": "SAI",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col/image.png",
    "number": 55,
    "car": "FERRARI",
    "dateOfBirth": "01/09/1994",
    "nationality": "Spanish",
    "placeOfBirth": "Madrid",
    "biografy": 'He’s the matador from Madrid racing royalty. Entering F1’s Bull Ring paired alongside Max Verstappen at Toro Rosso in 2015, Sainz quickly showed his fighting spirit. A tenacious racer, Sainz puts the car on the edge as he hustles his way through the pack. No wonder he’s earned the nickname Chilli.',
    "championshipsWon": 0,
    "podiums": 2,
    "participatingGPs": 121,
    "highestposGPs": '2 (x1)',
    "earnedPoint": 386,
    "polePosition": 7,
    "lat": 40.4384,
    "lng": -3.70992
  },
  {
    "driverId": 12,
    "firstName": "Yuki",
    "lastName": "Tsunoda",
    "driverRef": "tsunoda",
    "code": "TSU",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col/image.png",
    "number": 22,
    "car": "ALPHATAURI HONDA",
    "dateOfBirth": "11/05/2000",
    "nationality": "Japanese",
    "placeOfBirth": "",
    "biografy": '',
    "championshipsWon": 0,
    "podiums": 12,
    "participatingGPs": 61,
    "highestposGPs": '1 (x2)',
    "earnedPoint": 421,
    "polePosition": 7,
    "lat": 35.7036,
    "lng": 139.420
  },
  {
    "driverId": 13,
    "firstName": "Lance",
    "lastName": "Stroll",
    "driverRef": "stroll",
    "code": "STR",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col/image.png",
    "number": 18,
    "car": "ASTON MARTIN MERCEDES",
    "dateOfBirth": "29/10/1998",
    "nationality": "Canadian",
    "placeOfBirth": "Sagamihara",
    "biografy": 'In tutta la storia della Formula 1, nessun pilota giapponese ha mai vinto un Gran Premio del Campionato del Mondo. Yuki Tsunoda potrebbe essere il primo? La Red Bull la pensa certamente di sì, con il giovane sulla strada per la sua squadra senior se continua a stupire come ha fatto negli ultimi anni.',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 2,
    "highestposGPs": '9 (x1)',
    "earnedPoint": 2,
    "polePosition": 0,
    "lat": 45.6838,
    "lng": -73.5826
  },
  {
    "driverId": 14,
    "firstName": "Kimi",
    "lastName": "Räikkönen",
    "driverRef": "raikkonen",
    "code": "RAI",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_R%C3%A4ikk%C3%B6nen/kimrai01.png.transform/2col/image.png",
    "number": 7,
    "car": "ALFA ROMEO RACING FERRARI",
    "dateOfBirth": "17/10/1979",
    "nationality": "Finnish",
    "placeOfBirth": "Espoo",
    "biografy": 'È il pilota automobilistico di fama mondiale che vuole solo essere lasciato solo. È a causa della natura aspra e grezza che ha ispirato la Sauber a dargli il suo debutto nel 2001 e a firmarlo nuovamente per il 2019. Ha vinto gare senza paura che hanno portato a vittorie McLaren memorabili. O latteggiamento di non morire mai che ha conquistato il titolo mondiale per la Ferrari.',
    "championshipsWon": 1,
    "podiums": 103,
    "participatingGPs": 334,
    "highestposGPs": '1 (x21)',
    "earnedPoint": 1863,
    "polePosition": 18,
    "lat": 60.2146,
    "lng": 24.6586
  },
  {
    "driverId": 15,
    "firstName": "Esteban",
    "lastName": "Ocon",
    "driverRef": "ocon",
    "code": "OCO",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/2col/image.png",
    "number": 31,
    "car": "ALPINE RENAULT",
    "dateOfBirth": "17/09/1996",
    "nationality": "French",
    "placeOfBirth": "Évreux",
    "biografy": 'Se cè una parola che domina la carriera di Esteban Ocon, è sacrificio. Il 2014 ha visto Ocon sfondare nel mondo delle monoposto, battendo un certo Max Verstappen al titolo europeo di F3. Sostenuto dalla Mercedes, ha vinto il titolo GP3 lanno successivo ed era a metà di una stagione di DTM nel 2016 quando gli è stata offerta la possibilità di sostituire Rio Haryanto .',
    "championshipsWon": 0,
    "podiums": 1,
    "participatingGPs": 69,
    "highestposGPs": '2 (x1)',
    "earnedPoint": 200,
    "polePosition": 0,
    "lat": 49.0396,
    "lng": 1.14842
  },
  {
    "driverId": 16,
    "firstName": "George",
    "lastName": "Russell",
    "driverRef": "russell",
    "code": "RUS",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/2col/image.png",
    "number": 63,
    "car": "WILLIAMS MERCEDES",
    "dateOfBirth": "15/02/1998",
    "nationality": "British",
    "placeOfBirth": "Kings Lynn",
    "biografy": 'È il pilota con il motto: In caso di dubbio, vai a tutto gas. George Russell ha vissuto fino ad oggi nella sua carriera in F1, superando il compagno di squadra stagionato Robert Kubica in tutti i 21 Gran Premi nella sua stagione da rookie, e ripetendo limpresa contro Nicolas Latifi, dimostrando che Williams ha ragione nellidentificarlo come un gran lavoratore e un talento tenace.',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 40,
    "highestposGPs": '9 (x1)',
    "earnedPoint": 3,
    "polePosition": 0,
    "lat": 52.7522,
    "lng": 0.42269
  },
  {
    "driverId": 17,
    "firstName": "Mick",
    "lastName": "Schumacher",
    "driverRef": "schumacher",
    "code": "MSC",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/M/MICSCH02_Mick_Schumacher/micsch02.png.transform/2col/image.png",
    "number": 47,
    "car": "HAAS FERRARI",
    "dateOfBirth": "22/03/1999",
    "nationality": "Swiss",
    "placeOfBirth": "",
    "biografy": '',
    "championshipsWon": 0,
    "podiums": 12,
    "participatingGPs": 61,
    "highestposGPs": '1 (x2)',
    "earnedPoint": 421,
    "polePosition": 7,
    "lat": 46.4662,
    "lng": 6.21508
  },
  {
    "driverId": 18,
    "firstName": "Pierre",
    "lastName": "Gasly",
    "driverRef": "gasly",
    "code": "GAS",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/2col/image.png",
    "number": 10,
    "car": "ALPHATAURI HONDA",
    "dateOfBirth": "07/02/1996",
    "nationality": "French",
    "placeOfBirth": "Vufflens-le-Chàteau",
    "biografy": 'Schumacher Junior, a member of the Ferrari Driver Academy, arrives in F1 with Haas after clinching the F2 title in 2020, to add to the F3 championship he won in 2018 – so there is zero suggestion he has been elevated to the top level of motorsport because of his name.',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 2,
    "highestposGPs": '16 (x2)',
    "earnedPoint": 0,
    "polePosition": 0,
    "lat": 49.5526,
    "lng": 1.09330
  },
  {
    "driverId": 19,
    "firstName": "Nicholas",
    "lastName": "Latifi",
    "driverRef": "latifi",
    "code": "LAT",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/N/NICLAF01_Nicholas_Latifi/niclaf01.png.transform/2col/image.png",
    "number": 6,
    "car": "WILLIAMS MERCEDES",
    "dateOfBirth": "29/06/1995",
    "nationality": "Canadian",
    "placeOfBirth": "Montreal",
    "biografy": 'Nicholas Latifi aveva 13 anni quando mosse i primi passi nel motorsport. Solo 11 anni dopo, è diventato un pilota di Formula 1 a tutti gli effetti. Quellascesa nella massima categoria delle corse è stata in gran parte grazie alla sua stagione più impressionante fino ad oggi in Formula 2 nel 2019, con Latifi - che aveva concluso un deludente nono posto nella classifica 2018 della serie  che ha tirato su i suoi stivali per rivendicare il secondo in campionato',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 19,
    "highestposGPs": '11 (x3)',
    "earnedPoint": 0,
    "polePosition": 0,
    "lat": 45.6838,
    "lng": -73.5826
  },
  {
    "driverId": 20,
    "firstName": "Nikita",
    "lastName": "Mazepin",
    "driverRef": "mazepin",
    "code": "MAZ",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/N/NIKMAZ01_Nikita_Mazepin/nikmaz01.png.transform/2col/image.png",
    "number": 9,
    "car": "HAAS FERRARI",
    "dateOfBirth": "02/03/1999",
    "nationality": "Russian",
    "placeOfBirth": "Mosca",
    "biografy": 'Nikita Mazepin potrebbe portare con sé una buona fetta di budget al team Haas, ma non lasciarti ingannare dal pensare che non abbia anche le capacità di guida per farlo. Il russo, il quarto a gareggiare in F1 dopo Vitaly Petrov, Sergey Sirotkin e Daniil Kvyat, ha un curriculum impressionante nelle formule junior, finendo secondo nel campionato GP3 2018 con quattro vittorie.',
    "championshipsWon": 0,
    "podiums": 0,
    "participatingGPs": 2,
    "highestposGPs": '17 (x1)',
    "earnedPoint": 0,
    "polePosition": 0,
    "lat": 56.4873,
    "lng": 37.4597
  }
]

}
