export class Piloti
{
static listaPil=[
  {
    "driverId": 1,
    "firstName": "Lewis",
    "lastName": "Hamilton",
    "driverRef": "hamilton",
    "code": "HAM",
    "number": 44,
    "car": "MERCEDES",
    "dateOfBirth": "07/01/1985",
    "nationality": "British",
    "lat": 51.9048,
    "lng": -0.19683
  },
  {
    "driverId": 2,
    "firstName": "SEBASTIAN",
    "lastName": "VETTEL",
    "driverRef": "vettel",
    "code": "VET",
    "image": "https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col/image.png",
    "number": 5,
    "car": "ASTON MARTIN MERCEDES",
    "dateOfBirth": "03/07/1987",
    "nationality": "German",
    "placeOfBirth": "Heppenheim",
    "biografy": "Nato e cresciuto come un toro, poi un cavallino rampante, e ora il volto dell' Aston Martin, il ragazzo dei primi successi della F1 aveva vinto più di tutti, sotto solo a due piloti, nella storia quando aveva solo 26 anni, incluso il ritorno a titoli mondiali tra il 2010 e il 2013. Oltre ai suoi quattro titoli mondiali, può vantare più di 50 pole position e vittorie in gara.",
    "championshipsWon": 4,
    "podiums": 121,
    "participatingGPs": 259,
    "winningGPs": 53,
    "lat": 49.6431,
    "lng": 8.66309
  },
  {
    "driverId": 3,
    "firstName": "Max",
    "lastName": "Verstappen",
    "driverRef": "verstappen",
    "code": "VER",
    "number": 33,
    "car": "RED BULL RACING HONDA",
    "dateOfBirth": "30/09/1997",
    "nationality": "Dutch",
    "lat": 50.926,
    "lng": 5.285
  },
  {
    "driverId": 4,
    "firstName": "Valtteri",
    "lastName": "Bottas",
    "driverRef": "bottas",
    "code": "BOT",
    "number": 77,
    "car": "MERCEDES",
    "dateOfBirth": "28/08/1989",
    "nationality": "Finnish",
    "lat": 60.094,
    "lng": 25.593
  },
  {
    "driverId": 5,
    "firstName": "Charles",
    "lastName": "Leclerc",
    "driverRef": "leclerc",
    "code": "LEC",
    "number": 16,
    "car": "FERRARI",
    "dateOfBirth": "16/10/1997",
    "nationality": "Monegasque",
    "lat": 43.7429,
    "lng": 7.42624
  },
  {
    "driverId": 6,
    "firstName": "Antonio",
    "lastName": "Giovinazzi",
    "driverRef": "giovinazzi",
    "code": "GIO",
    "number": 99,
    "car": "ALFA ROMEO RACING FERRARI",
    "dateOfBirth": "14/12/1993",
    "nationality": "Italian",
    "lat": 40.7024,
    "lng": 17.3383
  },
  {
    "driverId": 7,
    "firstName": "Fernando",
    "lastName": "Alonso",
    "driverRef": "alonso",
    "code": "ALO",
    "number": 14,
    "car": "ALPINE RENAULT",
    "dateOfBirth": "29/07/1981",
    "nationality": "Spanish",
    "lat": 43.3638,
    "lng": -5.84917
  },
  {
    "driverId": 8,
    "firstName": "Lando",
    "lastName": "Norris",
    "driverRef": "norris",
    "code": "NOR",
    "number": 4,
    "car": "MCLAREN MERCEDES",
    "dateOfBirth": "13/11/1999",
    "nationality": "British",
    "lat": 51.4654,
    "lng": -2.58935
  },
  {
    "driverId": 9,
    "firstName": "Sergio",
    "lastName": "Perez",
    "driverRef": "perez",
    "code": "PER",
    "number": 11,
    "car": "RED BULL RACING HONDA",
    "dateOfBirth": "26/1/1990",
    "nationality": "Mexican",
    "lat": 20.7855,
    "lng": -103.346
  },
  {
    "driverId": 10,
    "firstName": "Daniel",
    "lastName": "Ricciardo",
    "driverRef": "ricciardo",
    "code": "RIC",
    "number": 3,
    "car": "MCLAREN MERCEDES",
    "dateOfBirth": "01/07/1989",
    "nationality": "Australian",
    "lat": -31.9060,
    "lng": 115.862
  },
  {
    "driverId": 11,
    "firstName": "Carlos",
    "lastName": "Sainz",
    "driverRef": "sainz",
    "code": "SAI",
    "number": 55,
    "car": "FERRARI",
    "dateOfBirth": "01/09/1994",
    "nationality": "Spanish",
    "lat": 40.4384,
    "lng": -3.70992
  },
  {
    "driverId": 12,
    "firstName": "Yuki",
    "lastName": "Tsunoda",
    "driverRef": "tsunoda",
    "code": "TSU",
    "number": 22,
    "car": "ALPHATAURI HONDA",
    "dateOfBirth": "11/05/2000",
    "nationality": "Japanese",
    "lat": 35.7036,
    "lng": 139.420
  },
  {
    "driverId": 13,
    "firstName": "Lance",
    "lastName": "Stroll",
    "driverRef": "stroll",
    "code": "STR",
    "number": 18,
    "car": "ASTON MARTIN MERCEDES",
    "dateOfBirth": "29/10/1998",
    "nationality": "Canadian",
    "lat": 45.6838,
    "lng": -73.5826
  },
  {
    "driverId": 14,
    "firstName": "Kimi",
    "lastName": "Räikkönen",
    "driverRef": "raikkonen",
    "code": "RAI",
    "number": 7,
    "car": "ALFA ROMEO RACING FERRARI",
    "dateOfBirth": "17/10/1979",
    "nationality": "Finnish",
    "lat": 60.2146,
    "lng": 24.6586
  },
  {
    "driverId": 15,
    "firstName": "Esteban",
    "lastName": "Ocon",
    "driverRef": "ocon",
    "code": "OCO",
    "number": 31,
    "car": "ALPINE RENAULT",
    "dateOfBirth": "17/09/1996",
    "nationality": "French",
    "lat": 49.0396,
    "lng": 1.14842
  },
  {
    "driverId": 16,
    "firstName": "George",
    "lastName": "Russell",
    "driverRef": "russell",
    "code": "RUS",
    "number": 63,
    "car": "WILLIAMS MERCEDES",
    "dateOfBirth": "15/02/1998",
    "nationality": "British",
    "lat": 52.7522,
    "lng": 0.42269
  },
  {
    "driverId": 17,
    "firstName": "Mick",
    "lastName": "Schumacher",
    "driverRef": "schumacher",
    "code": "MSC",
    "number": 47,
    "car": "HAAS FERRARI",
    "dateOfBirth": "22/03/1999",
    "nationality": "Swiss",
    "lat": 46.4662,
    "lng": 6.21508
  },
  {
    "driverId": 18,
    "firstName": "Pierre",
    "lastName": "Gasly",
    "driverRef": "gasly",
    "code": "GAS",
    "number": 10,
    "car": "ALPHATAURI HONDA",
    "dateOfBirth": "07/02/1996",
    "nationality": "French",
    "lat": 49.5526,
    "lng": 1.09330
  },
  {
    "driverId": 19,
    "firstName": "Nicholas",
    "lastName": "Latifi",
    "driverRef": "latifi",
    "code": "LAT",
    "number": 6,
    "car": "WILLIAMS MERCEDES",
    "dateOfBirth": "29/06/1995",
    "nationality": "Canadian",
    "lat": 45.6838,
    "lng": -73.5826
  },
  {
    "driverId": 20,
    "firstName": "Nikita",
    "lastName": "Mazepin",
    "driverRef": "mazepin",
    "code": "MAZ",
    "number": 9,
    "car": "HAAS FERRARI",
    "dateOfBirth": "02/03/1999",
    "nationality": "Russian",
    "lat": 56.4873,
    "lng": 37.4597
  }
]

}
