export class Scuderie
{
 static listascud = [
  {
    "constructorId": 1,
    "constructorRef": "mercedes",
    "name": "Mercedes-AMG Petronas F1 Team",
    "image": "http://cdn.mashup-web.com/img/categories/mercedes-amg.png",
    "firstTeamEntry": 1970,
    "Base": "Brackley",
    "Country": "United Kingdom",
    "WorldChampionships": 7,
    "HighestRaceFinish": "1(x107)",
    "Pole Positions": 119,
    "FastestLaps": 77,
    "CurrentPilots": "Lewis Hamilton, Valtteri Bottas",
    "lat": 52.0278,
    "lng": -1.14291
  },
  {
    "constructorId": 2,
    "constructorRef": "red bull",
    "name": "Red Bull Racing Honda",
    "image":"http://assets.stickpng.com/thumbs/580b57fcd9996e24bc43c1e8.png",
    "firstTeamEntry": 1997,
    "Base": "Milton Keynes",
    "Country": "United Kingdom",
    "WorldChampionships": 4,
    "HighestRaceFinish": "1(x65)",
    "PolePositions": 64,
    "FastestLaps": 68,
    "CurrentPilots": "Max Verstappen, Sergio Perez",
    "lat": 52.0401,
    "lng": -0.75927
  },
  {
    "constructorId": 3,
    "constructorRef": "mclaren",
    "name": "McLaren F1 Team",
    "image": "https://www.valvolepistoni.it/new/wp-content/uploads/2017/04/McLaren-logo-2002-2560x1440.png" ,
    "firstTeamEntry": 1966,
    "Base": "Woking",
    "Country": "United Kingdom",
    "WorldChampionships": 8,
    "HighestRaceFinish": "1(x182)",
    "PolePositions": 155,
    "FastestLaps": 158,
    "CurrentPilots": "Daniel Ricciardo, Lando Norris",
    "lat": 51.3164,
    "lng": -0.56066
  },
  {
    "constructorId": 4,
    "constructorRef": "ferrari",
    "name": "Scuderia Mission Winnow Ferrari",
    "image":"https://upload.wikimedia.org/wikipedia/it/thumb/5/59/Logo_della_Scuderia_Ferrari_%28vecchio%29.svg/1200px-Logo_della_Scuderia_Ferrari_%28vecchio%29.svg.png",
    "firstTeamEntry": 1950,
    "Base": "Maranello",
    "Country": "Italy",
    "WorldChampionships": 16,
    "HighestRaceFinish": "1(x239)",
    "PolePositions": 221,
    "FastestLaps": 253,
    "CurrentPilots": "Charles Leclerc, Carlos Sainz",
    "lat": 44.5266,
    "lng": 10.8674
  },
  {
    "constructorId": 5,
    "constructorRef": "alphatauri",
    "name": "Scuderia AlphaTauri Honda",
    "image":"https://upload.wikimedia.org/wikipedia/it/8/8e/Scuderia_AlphaTauri.png",
    "firstTeamEntry": 1985,
    "Base": "Faenza",
    "Country": "Italy",
    "WorldChampionships": "not any",
    "HighestRaceFinish": "1(x2)",
    "PolePositions": 1,
    "FastestLaps": 1,
    "CurrentPilots": "Pierre Gasly, Yuki Tsunoda",
    "lat": 44.2891,
    "lng": 11.8775
  },
  {
    "constructorId": 6,
    "constructorRef": "aston martin",
    "name": "Aston Martin Cognizant F1 Team",
    "image": "https://www.targetmotori.com/wp-content/uploads/2021/03/aston-martin-f1-logo.png",
    "firstTeamEntry": 2018,
    "Base": "Silverstone",
    "Country": "United Kingdom",
    "WorldChampionships": "not any",
    "HighestRaceFinish": "1(x1)",
    "PolePositions": 1,
    "FastestLaps": "not any",
    "CurrentPilots": "Sebastian Vettel, Lance Stroll",
    "lat": 52.0913,
    "lng": -1.02836
  },
  {
    "constructorId": 7,
    "constructorRef": "alfa romeo",
    "name": "Alfa Romeo Racing ORLEN",
    "image": "https://www.formula1.com/content/fom-website/en/teams/Alfa-Romeo-Racing/_jcr_content/logo.img.jpg/1582650443223.jpg",
    "firstTeamEntry": 1993,
    "Base": "Hinwil",
    "Country": "Switzerland",
    "WorldChampionships": "not any",
    "HighestRaceFinish": "1(x1)",
    "PolePositions": 1,
    "FastestLaps": 5,
    "CurrentPilots": "Kimi Raikkonen, Antonio Giovinazzi",
    "lat": 47.303,
    "lng": 8.8371
  },
  {
    "constructorId": 8,
    "constructorRef": "alpine",
    "name": "Alpine F1 Team",
    "image":"https://www.formula1.com/content/fom-website/en/teams/Alpine/_jcr_content/logo.img.jpg/1611246775071.jpg",
    "firstTeamEntry": 1986,
    "Base": "Enstone",
    "Country": "United Kingdom",
    "WorldChampionships":	2 ,
    "HighestRaceFinish": "1(x20)",
    "PolePositions":20 ,
    "FastestLaps": 15,
    "CurrentPilots": "Fernando Alonso, Esteban Ocon",
    "lat": 51.9199,
    "lng": -1.45578
  },
  {
    "constructorId": 9,
    "constructorRef": "williams",
    "name": "Williams Racing",
    "image":"https://www.formula1.com/content/fom-website/en/teams/Williams/_jcr_content/logo.img.jpg/1590743675531.jpg",
    "firstTeamEntry": 1978,
    "Base": "Grove",
    "Country": "United Kingdom",
    "WorldChampionships": 9,
    "HighestRaceFinish": "1(x114)",
    "PolePositions": 129,
    "FastestLaps": 133,
    "CurrentPilots": "George Russell, Nicholas Latifi",
    "lat": 51.6129,
    "lng": -1.41958
  },
  {
    "constructorId": 10,
    "constructorRef": "haas",
    "name": "Uralkali Haas F1 Team",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_Haas_F1.png",
    "firstTeamEntry": 2016,
    "Base": "Kannapolis",
    "Country": "United States",
    "WorldChampionships": "not any",
    "HighestRaceFinish": "4(x1)",
    "PolePositions": "not any",
    "FastestLaps": 2,
    "CurrentPilots": "Mick Schumacher, Nikita Mazepin",
    "lat": 35.4863,
    "lng": -80.6228
  }
]

}
