export class Scuderie
{
 static listascud = [
  {
    "constructorId": 1,
    "constructorRef": "mercedes",
    "name": "Mercedes-AMG Petronas F1 Team",
    "firstTeamEntry": 1970,
    "Base": "Brackley",
    "Country": "United Kingdom",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 52.0278,
    "lng": -1.14291
  },
  {
    "constructorId": 2,
    "constructorRef": "red bull",
    "name": "Red Bull Racing Honda",
    "firstTeamEntry": 1997,
    "Base": "Milton Keynes",
    "Country": "United Kingdom",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 52.0401,
    "lng": -0.75927
  },
  {
    "constructorId": 3,
    "constructorRef": "mclaren",
    "name": "McLaren F1 Team",
    "firstTeamEntry": 1966,
    "Base": "Woking",
    "Country": "United Kingdom",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 51.3164,
    "lng": -0.56066
  },
  {
    "constructorId": 4,
    "constructorRef": "ferrari",
    "name": "Scuderia Mission Winnow Ferrari",
    "firstTeamEntry": 1950,
    "Base": "Maranello",
    "Country": "Italy",
    "World Championships": 16,
    "Highest Race Finish": "1(x239)",
    "Pole Positions": 221,
    "Fastest Laps": 253,
    "Current Pilots": "Charles Leclerc, Carlos Sainz",
    "lat": 44.5266,
    "lng": 10.8674
  },
  {
    "constructorId": 5,
    "constructorRef": "alphatauri",
    "name": "Scuderia AlphaTauri Honda",
    "firstTeamEntry": 1985,
    "Base": "Faenza",
    "Country": "Italy",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 44.2891,
    "lng": 11.8775
  },
  {
    "constructorId": 6,
    "constructorRef": "aston martin",
    "name": "Aston Martin Cognizant F1 Team",
    "firstTeamEntry": 2018,
    "Base": "Silverstone",
    "Country": "United Kingdom",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 52.0913,
    "lng": -1.02836
  },
  {
    "constructorId": 7,
    "constructorRef": "alfa romeo",
    "name": "Alfa Romeo Racing ORLEN",
    "firstTeamEntry": 1993,
    "Base": "Hinwil",
    "Country": "Switzerland",
    "World Championships": "not any",
    "Highest Race Finish": "1(x1)",
    "Pole Positions": 1,
    "Fastest Laps": 5,
    "Current Pilots": "Kimi Raikkonen, Antonio Giovinazzi",
    "lat": 47.303,
    "lng": 8.8371
  },
  {
    "constructorId": 8,
    "constructorRef": "alpine",
    "name": "Alpine F1 Team",
    "firstTeamEntry": 1986,
    "Base": "Enstone",
    "Country": "United Kingdom",
    "World Championships":0 ,
    "Highest Race Finish": 0,
    "Pole Positions":0 ,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 51.9199,
    "lng": -1.45578
  },
  {
    "constructorId": 9,
    "constructorRef": "williams",
    "name": "Williams Racing",
    "firstTeamEntry": 1978,
    "Base": "Grove",
    "Country": "United Kingdom",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 51.6129,
    "lng": -1.41958
  },
  {
    "constructorId": 10,
    "constructorRef": "haas",
    "name": "Uralkali Haas F1 Team",
    "firstTeamEntry": 2016,
    "Base": "Kannapolis",
    "Country": "United States",
    "World Championships": 0,
    "Highest Race Finish": 0,
    "Pole Positions": 0,
    "Fastest Laps": 0,
    "Current Pilots": 0,
    "lat": 35.4863,
    "lng": -80.6228
  }
]

}
